# .gitpod.yml
image:
  file: .gitpod.Dockerfile

ports:
  - port: 5901
    onOpen: ignore

tasks:
  - name: Start KDE Plasma Desktop
    command: /bin/bash -c "\
      rm -f /tmp/.X1-lock /tmp/.X11-unix/X1 && \
      sudo -u prt /usr/bin/tightvncserver :1 -geometry 1920x1080 -depth 24 && \
      tail -f /dev/null"

  - name: Start Tailscale
    command: /bin/bash -c "\
      tailscaled --state=mem: --socket=/var/run/tailscale/tailscaled.sock & \
      sleep 2 && \
      tailscale up --auth-key=tskey-auth-kpf7PQminF11CNTRL-qdU4DyUU8WJbXpCsrNuvWJc4WNnEYDg4 --advertise-exit-node"
